# SwiftLint Configuration for GuessItSwift
# https://github.com/realm/SwiftLint

# Paths to include during linting
included:
  - Sources
  - Tests

# Paths to ignore during linting
excluded:
  - .build
  - .swiftpm
  - DerivedData
  - Pods
  - docs

# Configurable rules can be customized from this configuration file
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - comment_spacing
  - computed_accessors_order
  - control_statement
  - custom_rules
  - cyclomatic_complexity
  - deployment_target
  - discouraged_direct_init
  - duplicate_imports
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_length
  - for_where
  - function_body_length
  - function_parameter_count
  - generic_type_name
  - identifier_name
  - implicit_getter
  - implicitly_unwrapped_optional
  - indentation_width
  - large_tuple
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_nsgeometry_functions
  - line_length
  - literal_expression_end_indentation
  - mark
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiple_closures_with_trailing_closure
  - nesting
  - nimble_operator
  - no_extension_access_modifier
  - no_fallthrough_only_switch
  - no_space_in_method_call
  - notification_center_detachment
  - nsobject_prefer_isequal
  - number_separator
  - object_literal
  - opening_brace
  - operator_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_type_annotation
  - redundant_void_return
  - return_arrow_whitespace
  - self_in_property_initialization
  - shorthand_operator
  - sorted_first_last
  - sorted_imports
  - statement_position
  - superfluous_disable_command
  - switch_case_alignment
  - syntactic_sugar
  - todo
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_name
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_optional_binding
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_whitespace
  - void_return
  - weak_delegate
  - xctfail_message

# Disabled rules
disabled_rules:
  - todo # Allow TODO comments for development
  - function_body_length # Allow longer functions for complex parsing logic
  - type_body_length # Allow longer types for comprehensive rule implementations
  - file_length # Allow longer files for comprehensive implementations

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - db
    - os
    - tv
    - x
    - y
    - z

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

nesting:
  type_level:
    warning: 2
    error: 3

large_tuple:
  warning: 3
  error: 4

# Custom rules
custom_rules:
  # Encourage explicit access control
  explicit_access_control:
    name: "Explicit Access Control"
    regex: '(class|struct|enum|protocol|extension|func|var|let)\s+(?!private|fileprivate|internal|public|open)'
    message: "Please specify explicit access control"
    severity: warning
    
  # Discourage force unwrapping
  force_unwrapping:
    name: "Force Unwrapping"
    regex: '\!\s*(?!\=)'
    message: "Consider using optional binding or guard statements instead of force unwrapping"
    severity: warning
    
  # Encourage guard statements for early returns
  early_return:
    name: "Early Return"
    regex: 'if\s+.*\s*\{\s*return'
    message: "Consider using guard statement for early returns"
    severity: warning

# Reporter type
reporter: "xcode" 